import type { Metadata } from "next";

export const SITE_URL = "https://powerbankbangladesh.com";
export const SITE_NAME = "Power Bank Bangladesh";

// Next replaces (not merges) `openGraph` and `twitter` per segment, so every
// public page builds its full set here, including the share image generated by
// app/opengraph-image.tsx (a page-level `openGraph` drops it otherwise).
const SHARE_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "Power Bank Bangladesh: generator sell, exchange, rental, service and spare parts",
};

export function pageMetadata({
  title,
  description,
  path,
}: {
  title: string;
  description: string;
  path: string;
}): Metadata {
  const socialTitle = title.includes(SITE_NAME) ? title : `${title} | ${SITE_NAME}`;
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      locale: "en_BD",
      url: path,
      title: socialTitle,
      description,
      images: [SHARE_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: socialTitle,
      description,
      images: [SHARE_IMAGE.url],
    },
  };
}

// schema.org data for Google's local results. Contact details must match
// CLAUDE.md "Business facts" exactly.
export const businessJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "@id": `${SITE_URL}/#organization`,
  name: SITE_NAME,
  url: SITE_URL,
  logo: `${SITE_URL}/pbb-logo.png`,
  email: "powerbankbd23@gmail.com",
  slogan: "You Believe, We Assure Trust",
  description:
    "Diesel generator dealer in Bangladesh: sell, exchange, rental, service and spare parts for all kinds of generators.",
  areaServed: { "@type": "Country", name: "Bangladesh" },
  contactPoint: [
    {
      "@type": "ContactPoint",
      telephone: "+8801989474447",
      contactType: "sales",
      areaServed: "BD",
      availableLanguage: ["en", "bn"],
    },
    {
      "@type": "ContactPoint",
      telephone: "+8801625181403",
      contactType: "customer service",
      areaServed: "BD",
      availableLanguage: ["en", "bn"],
    },
  ],
  department: [
    {
      "@type": "LocalBusiness",
      name: `${SITE_NAME} (Dhaka)`,
      image: `${SITE_URL}/pbb-logo.png`,
      telephone: "+8801989474447",
      email: "powerbankbd23@gmail.com",
      address: {
        "@type": "PostalAddress",
        streetAddress: "Kamalapur, Biruliya",
        addressLocality: "Savar",
        addressRegion: "Dhaka",
        addressCountry: "BD",
      },
    },
    {
      "@type": "LocalBusiness",
      name: `${SITE_NAME} (Chattogram)`,
      image: `${SITE_URL}/pbb-logo.png`,
      telephone: "+8801989474447",
      email: "powerbankbd23@gmail.com",
      address: {
        "@type": "PostalAddress",
        streetAddress:
          "Shop: 8, Subashati Chawk Arcade, 174/A, Nawab Siraj Ud Daulah Road, Chawkbazar",
        addressLocality: "Chattogram",
        addressCountry: "BD",
      },
    },
  ],
  makesOffer: [
    "Generator Sales",
    "Generator Exchange",
    "Generator Rental",
    "Generator Service and Repair",
    "Generator Spare Parts",
  ].map((name) => ({
    "@type": "Offer",
    itemOffered: { "@type": "Service", name, areaServed: "Bangladesh" },
  })),
};
